### ISSUE TITLE
This app does not run...

### ISSUE THREAD

**Issue by enetstudio** [cradle77/BlazorSecurityDemo#3]
I'm in the habit of downloading and running code before reading an article related to it. If the code doe not work I just give up reading the article. Please, download this app, and run it as is, and tell us how to fix the issue.

Thanks in advance...

**Comment by cradle77** [comment]
Hi,

Thanks for your message. The application does run as it is, however Visual Studio with the default options tries to run it in IISExpress which doesn't have the correct URLs set - VS Code doesn't have this issue.

I've forced the execution with Kestrel and added a handy README file.

Enjoy.

**Comment by enetstudio** [comment]
I thank you for the time you took to respond... However, this surely can't work, as the order of the projects in the Multiple startup projects is wrong. It should be:  IdentityProvider => BlazorClient => WeatherApi But in order to make it work... now working perfectly well, I had to swap the locations of the profiles section items in all the launchSettings.json files. As for instance, instead of this:
```
"profiles": {
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "launchUrl": "https://localhost:5000",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    },
    "SelfHost": {
      "commandName": "Project",
      "launchBrowser": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      },
      "applicationUrl": "https://localhost:5000"
    }
  }
```

use the following:

```
"profiles": {
    "SelfHost": {
      "commandName": "Project",
      "launchBrowser": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      },
      "applicationUrl": "https://localhost:5000"
    },
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "launchUrl": "https://localhost:5000",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    }
```

 I greatly thank you for this excellent article. Learned lots...
