### ISSUE TITLE
Example with Custom User Store

### ISSUE THREAD

**Issue by kevonh** [cradle77/BlazorSecurityDemo#4]
It would be nice if you could provide an example where this works with a custom user store, not using EntityFramework, but perhaps Dapper.

I don't want to be tied to the default user stores and EntityFramework integration.

**Comment by cradle77** [comment]
Hello, I agree with you, it would be interesting, however I feel it's a bit out of scope for what I'm demoing here, which is how Blazor and IS4 integrate.

There are a few examples around the internet you can follow:
e.g. https://damienbod.com/2017/04/14/asp-net-core-identityserver4-resource-owner-password-flow-with-custom-userrepository/
